### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SeiyaGame** [SeiyaGame/fan_control_supermicro#9]
- [x] Remove SSD from list disk
- [x] Check if `config.py` exist or print a message and exit
- [x] Send webhook if a specific temperature is reach
- [x] Move grid fan speed into an another file (`config.py`)
- [x]  Grid fan speed allow non range value ( Able to have an int and not only tuple)
- [X] Fix DISCORD_WEBHOOK_LOGS in config , not working
- [ ] Add an command to watch logs ? (temporary added an alias to bashrc)
- [x] Send webhook of all disk that reach specific temperature
- [x] Send webhook of all disk that reach a too low temperature
- [x] Metrics with prometheus exporter
- [ ] Create a docker ?
- [ ] Add requirements.txt for other distribution than Truenas Scale
- [ ] Add precheck to unsure that `ipmitools` and `smartctl` is available
- [ ] A better README to explicitly said that this script as some limitation duo to Truenas Scale ( Unable to install package and  pip module etc)
- [ ] README add manuel step on how to setup the script with systemd service
- [ ] README explains that the fans must be set to FULL to be controlled

**Comment by nickheyer** [comment]
Want help? I've got the following in my rack:

4x X10DRU-i+ (dual xeons in each)
1x X9
6x X11

and the latest addition is:

h12DSi-N6 (dual amd epyx milan 64 cores + nvidia pro 6000 blackwell)

**Comment by SeiyaGame** [comment]
> Want help? I've got the following in my rack:
> 
> 4x X10DRU-i+ (dual xeons in each) 1x X9 6x X11
> 
> and the latest addition is:
> 
> h12DSi-N6 (dual amd epyx milan 64 cores + nvidia pro 6000 blackwell)

Help is welcome, as I only have a Supermicro H11SSL-i running Truenas Scale.
Note that @pixelpunk-DE has been tested with an `A2SDi-HLN4F` motherboard and it seems to work fine :D
There shouldn't be any reason it wouldn't work on other motherboards either.
